Import the required packages

In [1]:
import numpy as np

1-Dimensional Array

In [2]:
arr_1D = np.array([1, 3, 5, 7, 11, 15, 12, 13, 20])
arr_1D

array([ 1,  3,  5,  7, 11, 15, 12, 13, 20])

In [3]:
type(arr_1D)

numpy.ndarray

In [4]:
arr_1D.ndim

1

In [5]:
arr_1D.shape

(9,)

2-Dimensional Array

In [6]:
arr_2D = np.array([[1, 3, 7], [2, 4, 6]])
arr_2D

array([[1, 3, 7],
       [2, 4, 6]])

In [7]:
type(arr_2D)

numpy.ndarray

In [8]:
arr_2D.ndim

2

In [9]:
arr_2D.shape

(2, 3)

To access the element: Random access in an array

In [10]:
arr_2D[1][1]

4

3-Dimensional Array

In [11]:
arr_3D = np.array([[[1,3], [2,4]], [[2,6], [7,9]]])
arr_3D

array([[[1, 3],
        [2, 4]],

       [[2, 6],
        [7, 9]]])

In [12]:
type(arr_3D)

numpy.ndarray

In [13]:
arr_3D.ndim

3

In [14]:
arr_3D.shape

(2, 2, 2)

In [18]:
arr_3D_v2 = np.array([[[1,3], [2,4]], [[2,6], [7,9]], [[2,3], [7,12]]])
arr_3D_v2

array([[[ 1,  3],
        [ 2,  4]],

       [[ 2,  6],
        [ 7,  9]],

       [[ 2,  3],
        [ 7, 12]]])

In [16]:
arr_3D_v2.shape

(3, 2, 2)

In [19]:
arr_3D_v2[1]

array([[2, 6],
       [7, 9]])

To access the element in 3D array

In [20]:
arr_3D_v2[1][1][1]

9

In [22]:
arr_3D_v2[2][1][1]

12

Built-in functions in Numpy

In [23]:
## Data Generation
## np.arange(start, stop[exclusive], step_size)
np.arange(1, 9, 2)

array([1, 3, 5, 7])

In [24]:
## generate the data points having even numbers only in the range from 2 to 100 (inclusive)
np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [25]:
np.linspace(1, 9, 7)

array([1.        , 2.33333333, 3.66666667, 5.        , 6.33333333,
       7.66666667, 9.        ])

In [26]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [27]:
## generate the data points having starting as 2, ending as 100 and the number of entries should be 20
np.linspace(2, 100, 20)

array([  2.        ,   7.15789474,  12.31578947,  17.47368421,
        22.63157895,  27.78947368,  32.94736842,  38.10526316,
        43.26315789,  48.42105263,  53.57894737,  58.73684211,
        63.89473684,  69.05263158,  74.21052632,  79.36842105,
        84.52631579,  89.68421053,  94.84210526, 100.        ])

Difference between shallow copy and deep copy

In [28]:
import copy
original_data = [[1, 2, 3], [4, 5, 6]]
shallow_copy_data = copy.copy(original_data)

print(original_data)

print(shallow_copy_data)

[[1, 2, 3], [4, 5, 6]]
[[1, 2, 3], [4, 5, 6]]


In [29]:
shallow_copy_data[0][2] = 10
print("Original list", original_data)
print("Shallow Copied list", shallow_copy_data)

Original list [[1, 2, 10], [4, 5, 6]]
Shallow Copied list [[1, 2, 10], [4, 5, 6]]


In [30]:
import copy
original_data = [[1, 2, 3], [4, 5, 6]]
deep_copy_data = copy.deepcopy(original_data)

print(original_data)

print(deep_copy_data)

[[1, 2, 3], [4, 5, 6]]
[[1, 2, 3], [4, 5, 6]]


In [32]:
deep_copy_data[0][2] = 10
print("Original list", original_data)
print("Deep Copied list", deep_copy_data)

Original list [[1, 2, 3], [4, 5, 6]]
Deep Copied list [[1, 2, 10], [4, 5, 6]]


fromfunction in numpy - Data Creation

In [33]:
np.fromfunction(lambda i, j: i*j, (5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  3.,  6.,  9., 12.],
       [ 0.,  4.,  8., 12., 16.]])

In [34]:
## Create a boolean matrix in which if the index numbers are same, return true otherwise return false and the size of the array should be (4,4)
np.fromfunction(lambda i, j: i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [35]:
## Create a dataset in the range from 2 to 9 having 50 entries in it
dataset = np.linspace(2, 9, 50)
dataset

array([2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
       2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
       3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
       4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
       4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143,
       5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
       6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
       7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
       7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
       8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ])

In [36]:
dataset.ndim

1

In [37]:
dataset.shape

(50,)

Reshape in numpy: change the shape of any dataset

In [38]:
## create 2 subarrays having size (1, 25)
result = dataset.reshape(2, 1, 25)
print(result)

[[[2.         2.14285714 2.28571429 2.42857143 2.57142857 2.71428571
   2.85714286 3.         3.14285714 3.28571429 3.42857143 3.57142857
   3.71428571 3.85714286 4.         4.14285714 4.28571429 4.42857143
   4.57142857 4.71428571 4.85714286 5.         5.14285714 5.28571429
   5.42857143]]

 [[5.57142857 5.71428571 5.85714286 6.         6.14285714 6.28571429
   6.42857143 6.57142857 6.71428571 6.85714286 7.         7.14285714
   7.28571429 7.42857143 7.57142857 7.71428571 7.85714286 8.
   8.14285714 8.28571429 8.42857143 8.57142857 8.71428571 8.85714286
   9.        ]]]


In [39]:
## Convert the dataset to 2 dimensions having shape as (2, 25)
result_2D = dataset.reshape(2, 25)
result_2D

array([[2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
        2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
        3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
        4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
        4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143],
       [5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
        6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
        7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
        7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
        8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ]])

In [41]:
## Convert the dataset to 2 dimensions having shape as (25, 2)
result_2D_v2 = dataset.reshape(25, 2)
result_2D_v2

array([[2.        , 2.14285714],
       [2.28571429, 2.42857143],
       [2.57142857, 2.71428571],
       [2.85714286, 3.        ],
       [3.14285714, 3.28571429],
       [3.42857143, 3.57142857],
       [3.71428571, 3.85714286],
       [4.        , 4.14285714],
       [4.28571429, 4.42857143],
       [4.57142857, 4.71428571],
       [4.85714286, 5.        ],
       [5.14285714, 5.28571429],
       [5.42857143, 5.57142857],
       [5.71428571, 5.85714286],
       [6.        , 6.14285714],
       [6.28571429, 6.42857143],
       [6.57142857, 6.71428571],
       [6.85714286, 7.        ],
       [7.14285714, 7.28571429],
       [7.42857143, 7.57142857],
       [7.71428571, 7.85714286],
       [8.        , 8.14285714],
       [8.28571429, 8.42857143],
       [8.57142857, 8.71428571],
       [8.85714286, 9.        ]])

In [ ]:
## Convert the original dataset to the size (25, 3)
## no, it's not possible (25*3 = 75)
## result_2D_v2 = dataset.reshape(25, 2)
result_2D_v2
result_2D_v3 = dataset.reshape(25, 3)
result_2D_v3

In [43]:
## Eigenvalues and Eigenvectors (Linear Algebra) [Machine Learning (PCA)]
array = np.array([[4, 2], [1, 3]])
eigenValue, eigenVector = np.linalg.eig(array)
print(eigenValue)
print(eigenVector)

[5. 2.]
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [44]:
array

array([[4, 2],
       [1, 3]])

In [51]:
array[:, 1:2]

array([[2],
       [3]])

In [56]:
array[: , [1]]

array([[2],
       [3]])

In [57]:
array[:, 1:]

array([[2],
       [3]])

In [54]:
array[:, :1]

array([[4],
       [1]])

Slicing operations in an array

In [58]:
array_v2 = np.array([[1, 2, 3], [4, 5, 6]])
array_v2

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
array_v2[:, 1:2]

array([[2],
       [5]])

In [60]:
array_v2[:, 1:]

array([[2, 3],
       [5, 6]])